version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/newfound
    binary: newfound
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc
